application: nacl-quake
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: quake.html
  upload: quake.html
- url: /(.+\.(nmf|nexe|html))
  static_files: \1
  upload: (.+\.(nmf|nexe|html))
  mime_type: application/x-nacl
- url: /(.+\.(css|js))
  static_files: \1
  upload: (.+\.(css|js))
- url: /id1/(.+)
  static_files: id1/\1
  upload: id1/(.+)

